services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:${HOST_PORT}"
    depends_on:
      - mongodb
    working_dir: /app
    command: yarn run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGO_URI: ${MONGO_URI}
    networks:
      - portfolio
  mongodb:
    image: mongo:latest
    container_name: mongodb_portfolio
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio

volumes:
  mongodb_data:

networks:
  portfolio: